"""Initial migration

Revision ID: 4cf3416153d6
Revises: 
Create Date: 2026-06-29 10:46:56.826503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cf3416153d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('addiction_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bad_habits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('good_habits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('exercise_frequency', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('recovery_style', sa.String(length=20), nullable=True),
    sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relapse_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('craving_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addiction_profiles_id'), 'addiction_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_addiction_profiles_user_id'), 'addiction_profiles', ['user_id'], unique=True)
    op.create_table('assessments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('addiction_type', sa.String(length=50), nullable=False),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('addiction_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('recovery_difficulty', sa.String(length=20), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('gamification',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_quests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recovery_tree_stage', sa.Integer(), nullable=False),
    sa.Column('discipline_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_id'), 'gamification', ['id'], unique=False)
    op.create_index(op.f('ix_gamification_user_id'), 'gamification', ['user_id'], unique=True)
    op.create_table('journal_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('emotion', sa.String(length=30), nullable=False),
    sa.Column('emotion_intensity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('people_context', sa.String(length=30), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('sleep_hours_last_night', sa.Float(), nullable=True),
    sa.Column('device', sa.String(length=20), nullable=True),
    sa.Column('trigger_app', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('weather', sa.String(length=30), nullable=True),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('recovery_scores',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=False),
    sa.Column('focus_score', sa.Integer(), nullable=False),
    sa.Column('exercise_score', sa.Integer(), nullable=False),
    sa.Column('meditation_score', sa.Integer(), nullable=False),
    sa.Column('screen_time_score', sa.Integer(), nullable=False),
    sa.Column('relapse_score', sa.Integer(), nullable=False),
    sa.Column('consistency_score', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_scores_id'), 'recovery_scores', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_scores_score_date'), 'recovery_scores', ['score_date'], unique=False)
    op.create_index(op.f('ix_recovery_scores_user_id'), 'recovery_scores', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('triggers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.String(length=200), nullable=False),
    sa.Column('pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_id'), 'triggers', ['id'], unique=False)
    op.create_index(op.f('ix_triggers_user_id'), 'triggers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triggers_user_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_id'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_recovery_scores_user_id'), table_name='recovery_scores')
    op.drop_index(op.f('ix_recovery_scores_score_date'), table_name='recovery_scores')
    op.drop_index(op.f('ix_recovery_scores_id'), table_name='recovery_scores')
    op.drop_table('recovery_scores')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_gamification_user_id'), table_name='gamification')
    op.drop_index(op.f('ix_gamification_id'), table_name='gamification')
    op.drop_table('gamification')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_addiction_profiles_user_id'), table_name='addiction_profiles')
    op.drop_index(op.f('ix_addiction_profiles_id'), table_name='addiction_profiles')
    op.drop_table('addiction_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
