"""Add RecoveryPlan model

Revision ID: 75c43cce42c9
Revises: 4cf3416153d6
Create Date: 2026-06-29 16:21:44.801733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c43cce42c9'
down_revision: Union[str, None] = '4cf3416153d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_phase_index', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_plans_id'), 'recovery_plans', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_plans_user_id'), 'recovery_plans', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_plans_user_id'), table_name='recovery_plans')
    op.drop_index(op.f('ix_recovery_plans_id'), table_name='recovery_plans')
    op.drop_table('recovery_plans')
    # ### end Alembic commands ###
